backend/apps/products/urls.py
from django.urls import path
from .views import CategoryListView, ProductListView, ProductDetailView

urlpatterns = [
    path('', CategoryListView.as_view(), name="categories_list"),
    path('<slug:slug>/', ProductListView.as_view(), name="products_list"),
    path('<slug:category_slug>/<int:pk>-<slug:slug>/', ProductDetailView.as_view(), name="product_detail"),
]

backend/backend/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from apps.my_auth.views import MyLoginView
from .sitemaps import StaticViewSitemap, CategorySitemap, ProductSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'categories': CategorySitemap,
    'products': ProductSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),

    path('accounts/login/', MyLoginView.as_view(), name='login'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('apps.my_auth.urls')),

    path('about/', include('apps.about.urls')),
    path('delivery/', include('apps.delivery.urls')),
    path('contacts/', include('apps.contacts.urls')),
    path('products/', include('apps.products.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/apps/products/models.py
from django.db import models
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from backend.abstract_models import SeoModel, TimeStampedModel


class CategoryManager(models.Manager):
    def enabled(self):
        """Возвращает категории с is_enabled=True."""
        return super(CategoryManager, self).get_queryset().filter(is_enabled=True)


class Category(SeoModel, TimeStampedModel):
    """Модель категории товаров."""
    title = models.CharField('Название', max_length=255)
    slug = models.SlugField(
        'Slug',
        max_length=255,
        unique=True,
        help_text='Используется при формировании ссылки на страницу категории.'
    )
    image = models.ImageField(
        'Изображение',
        upload_to='categories/',
        blank=True,
        null=True,
        help_text='Оптимальное разрешение - 400px * 270px'
    )
    text = RichTextUploadingField('Текст', blank=True, null=True)
    weight = models.PositiveIntegerField(
        'Вес',
        help_text='Чем больше вес, тем "выше" категория отображается на странице.',
        default=1
    )
    is_enabled = models.BooleanField('Включено', default=True)

    objects = CategoryManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('products_list', args=[self.slug])

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('title',)


class Car(TimeStampedModel):
    """Модель автомобиля (модели)."""
    title = models.CharField('Название', max_length=255)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Модель автомобиля'
        verbose_name_plural = 'Модели автомобилей'
        ordering = ('title',)


class ProductManager(models.Manager):
    def enabled(self):
        """Возвращает товары с is_enabled=True."""
        return super(ProductManager, self).get_queryset().filter(
            is_enabled=True,
            category__isnull=False,
            category__is_enabled=True
        )


class Product(SeoModel, TimeStampedModel):
    """Модель товара."""
    CURRENCIES = (
        (1, 'Гривна'),
        (2, 'Доллар'),
    )

    title = models.CharField('Название', max_length=255)
    slug = models.SlugField(
        'Slug',
        max_length=255,
        help_text='Используется при формировании ссылки на страницу товара.'
    )
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, verbose_name='Категория', null=True, blank=True)
    text = RichTextUploadingField('Текст', blank=True, null=True)
    car = models.ForeignKey(Car, on_delete=models.SET_NULL, verbose_name='Подходит для', blank=True, null=True)
    price = models.PositiveIntegerField('Стоимость', blank=True, null=True)
    currency = models.PositiveSmallIntegerField(
        'Валюта',
        choices=CURRENCIES,
        default=1
    )
    in_stock = models.BooleanField('В наличии', default=True)
    is_enabled = models.BooleanField('Включено', default=True)

    objects = ProductManager()

    def __str__(self):
        return self.title

    def get_first_photo(self):
        """Возвращает первую фотографию продукта или None, если изображений нету."""
        image = self.productphoto_set.filter(is_visible=True).order_by('created_at').first()
        if not image:
            return None
        return image

    def get_photos(self):
        """Возвращает все видимые фотографии продукта."""
        return self.productphoto_set.filter(is_visible=True).order_by('created_at')

    def get_absolute_url(self):
        if self.category:
            return reverse('product_detail', args=[self.category.slug, self.pk, self.slug])
        return '/'

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ('-created_at',)
        permissions = (("can_see_price", "Может смотреть цену"),)


class ProductPhoto(TimeStampedModel):
    """Модель фотографии товара."""

    def upload_to(instance, filename):
        return 'products/{}/{}'.format(instance.product.pk, filename)

    image = models.ImageField(
        'Изображение',
        upload_to=upload_to,
        help_text='Оптимальный размер: 800px*500px.'
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')
    is_visible = models.BooleanField('Включено', default=True)

    def __str__(self):
        return 'Изображение #{}'.format(self.pk)

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Галерея товара'
        ordering = ('created_at',)

backend/apps/products/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.http import Http404
from .models import Category, Product


class CategoryListView(ListView):
    """Отображает страницу со списком категорий."""
    queryset = Category.objects.enabled().order_by('-weight')
    template_name = 'products/categories/list.html'


class ProductListView(ListView):
    """Отображает страницу со списком продуктов конкретной категории."""
    template_name = 'products/products/list.html'
    paginate_by = 9

    def get_queryset(self):
        return Product.objects.enabled().filter(category__slug=self.kwargs['slug']).order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['category'] = Category.objects.enabled().filter(slug=self.kwargs['slug']).first()
        if not context['category']:
            raise Http404('Категория не включена.')
        context['categories'] = Category.objects.enabled().order_by('-weight')
        return context


class ProductDetailView(DetailView):
    """Отображает страницу товара."""
    queryset = Product.objects.enabled()
    template_name = 'products/product/detail.html'

backend/apps/products/templates/products/categories/_partials/breadcrumbs.html
<section class="g-bg-gray-light-v5 g-py-50">
    <div class="container">
        <div class="d-sm-flex text-center">
            <div class="align-self-center">
                <h1 class="h3 g-font-weight-300 w-100 g-mb-10 g-mb-0--md">{% if page_data.meta_h1 %}{{ page_data.meta_h1 }}{% else %}Категории товаров{% endif %}</h1>
            </div>

            <div class="align-self-center ml-auto">
                <ul class="u-list-inline">
                    <li class="list-inline-item g-mr-5">
                        <a class="u-link-v5 g-color-main" href="/">Главная</a>
                        <i class="g-color-gray-light-v2 g-ml-5">/</i>
                    </li>
                    <li class="list-inline-item g-color-primary">
                        <span>Категории товаров</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>

backend/apps/products/templates/products/categories/_partials/categories_list.html
{% load thumbnail %}

<section>
    <div class="container g-py-100">
        <div class="row g-mb-30">
            <div class="col-12">
                <p class="g-font-size-16">Выбирайте интересующую вас категорию:</p>
            </div>
        </div>

        <div class="row text-center">
            {% for category in category_list %}
                <div class="col-md-4 g-mb-30">
                    <a class="d-block u-block-hover u-bg-overlay g-bg-black-opacity-0_5--after" href="{% url 'products_list' slug=category.slug %}">
                        {% if category.image %}
                            <img class="img-fluid u-block-hover__main--zoom-v1"
                                 src="{{ category.image|thumbnail_url:'category' }}"
                                 alt="{{ category.title }}">
                        {% else %}
                            <img class="img-fluid u-block-hover__main--zoom-v1"
                                 src="//via.placeholder.com/400x270?text=No+Image"
                                 alt="Изображение отсутствует">
                        {% endif %}
                        <strong class="h4 d-block w-100 u-bg-overlay__inner g-absolute-centered g-px-20 g-font-weight-400 g-color-white g-mt-10">{{ category.title }}</strong>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</section>